name: run2 ws.py

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  run_chedule:
    runs-on: ubuntu-latest
    steps:

      - name: 'Check repositorio'
        uses: actions/checkout@v4

      - name: 'Installar Python'
        uses: actions/setup-python@v4

      - name: 'instalar os pacotes do requirements.txt'
        run: python -m pip install pip install -r requirements.txt

      - name: 'executar scrapping'
        run: python ws.py
