name: run2 ws.py

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  run_chedule:
    runs-on: ubuntu-latest
    steps:

      - name: 'Check repositorio'
        uses: actions/checkout@v4
     
      - name: 'Configurar Variáveis de Ambiente'
        run: |
          echo "GMAIL_USERNAME=${{ secrets.GMAIL_USERNAME }}" >> $GITHUB_ENV
          echo "GMAIL_PASSWORD=${{ secrets.GMAIL_PASSWORD }}" >> $GITHUB_ENV
          echo "DESTINATION_EMAIL=${{ secrets.DESTINATION_EMAIL }}" >> $GITHUB_ENV


      - name: 'Installar Python'
        uses: actions/setup-python@v4

      - name: 'instalar os pacotes do requirements.txt'
        run: python -m pip install pip install -r requirements.txt

      - name: 'executar scrapping'
        run: python ws.py
        env:
          GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
          DESTINATION_EMAIL: ${{ secrets.DESTINATION_EMAIL }}
