name: run ws.py

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  run_schedule:
    runs-on: ubuntu-latest
    steps:
  
      - name: Check conteudo repositorio
        uses: actions/checkout@v4
  
      - name: instalar python
        uses: actions/setup-python@v4
  
      - name: instalar os pacotes do requirements.txt
        run: python -m pip install pip install -r requirements.txt
  
      - name: executar script scrapping
        run: python ws.py
